# asc config
ntasks: 19
idrandom: 0
train_data_size: 0

# training config
train_epochs: 2

# static
checkpoint_path: "/data3/zl/lifelong/checkpoints/asc/bert"
bert_model: "zoo/bert/"
eval_batch_size: 8
max_seq_length: 128
exp: ""
max_term_length: 5

# dynamic
bert_hidden_size: 768
hidden_dropout_prob: 0.1
train_batch_size: 32
learning_rate: 1e-5
