# dsc config
ntasks: 1
num_labels: 2
idrandom: 0
train_data_size: 0

# training config
train_epochs: 2

# static
checkpoint_path: "/data3/zl/lifelong/checkpoints/dsc/bert"
bert_model: "zoo/bert/"
eval_batch_size: 8
max_seq_length: 256

# dynamic
hidden_size: 128
num_neurons: 128
bert_hidden_size: 768
train_batch_size: 16
learning_rate: 0.00001
dropout_probability: 0.5
