# dsc config
task: "dsc"
ntasks: 3
num_labels: 2
idrandom: 0
train_data_size: 0

# training config
seed: 1024
train_epochs: 2

# static
checkpoint_path: "/data3/zl/lifelong/checkpoints/bert"
bert_model: "zoo/bert/"
eval_batch_size: 8
max_seq_length: 128

# dynamic
bert_hidden_size: 768
hidden_dropout_prob: 0.1
train_batch_size: 32
learning_rate: 1e-5
